service: front-end
runtime: python27
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

# TODO needed?
libraries:
- name: PIL
  version: latest
